export enum Services {
  AUTH_SERVICE = 'AUTH_SERVICE',
  WALLET_SERVICE = 'WALLET_SERVICE',
  ORDERS_SERVICE = 'ORDERS_SERVICE',
  INTERGRATION_SERVICE = 'INTERGRATION_SERVICE',
}

export enum Actions {}
